sudo: false
language: groovy
jdk:
 - oraclejdk8
branches:
 only:
 - master

before_script:
 - chmod +x grailsw

script: ./grailsw stats
 && chmod +x /home/travis/.grails/wrapper/2.3.11/grails-2.3.11/bin/grails
 && ./grailsw compile --refresh-dependencies
 && ./grailsw test-app
